### ISSUE TITLE
Vài lỗi sau khi merge toàn bộ (trừ Bai5) nhánh vào develop

### ISSUE THREAD

**Issue by grintondh** [grintondh/LearningSystem#22]
**1. Lỗi khi editing question**
![image](https://github.com/grintondh/LearningSystem/assets/90957755/665f8663-8ee7-445c-bac0-3b3505f4aedd)

**2. Sau khi thêm Category chưa hiện số câu ở cuối** 
![image](https://github.com/grintondh/LearningSystem/assets/90957755/2bc5b003-06cb-4698-8ba1-e4fdefc47101)

**3. Sau khi export từ Word thì không xuất hiện câu đó trong Export**

**Comment by elio-perlman-13** [comment]
3. kh hiểu lắm tại nãy t test thì 2 câu 61 62 export từ word vẫn xuất hiện trong file pdf á
![image](https://github.com/grintondh/LearningSystem/assets/129037773/cce27cac-1891-4f21-99b3-0703154ce98d)

**Comment by elio-perlman-13** [comment]
![image](https://github.com/grintondh/LearningSystem/assets/129037773/6d49476c-0fdb-4af2-b1f5-c9c671f86a69)
với cả nó vẫn bị outofexception khi edit câu hỏi nè

**Comment by NgxLama** [comment]
Có phải câu hỏi được edit đang thuộc category Lý dễ đúng k nhỉ. File category này có vẻ đang có vấn đề vì trong Category.json thì Lý dễ có chứa các câu id 5 6 7 8 nhưng trong Question.json thì 9 10 cũng thuộc vào Lý dễ. Cái lỗi file này cũng dẫn đến lúc mở combobox chọn category thì hiển thị Lý dễ có 4 câu nhưng có 6 câu được hiển thị trong datagridview

**Comment by NgxLama** [comment]
à không lỗi là do đg edit câu hỏi trong subcategory nma code tôi lại sửa category cha nên nó bị lỗi =(( để tôi suy nghĩ thêm rồi fix nhé =((

**Comment by NgxLama** [comment]
à không lỗi là do đg edit câu hỏi trong subcategory nma code tôi lại sửa category cha nên nó bị lỗi =(( để thi xong có tgian rồi tôi fix dần nhé =((

**Comment by NgxLama** [comment]
Done
