### ISSUE TITLE
Update branch Develop (Bai 6 - 7)

### ISSUE THREAD

**Issue by grintondh** [grintondh/LearningSystem#31]
- [x] Tạo branch backup_develop từ bản hiện tại. Nếu không kịp sửa chữa thì sẽ merge backup_develop với main.

**Note: Các commit cần note xem đang / đã sửa mục nào.** 
**Hoàn thành trước 8/7**

*Contest information*

- [ ] Các thông tin kỳ thi (time limit, grading method), nút Preview quiz now cần căn giữa. @Jeff-kxng 
- [x] Time Limit cần hiển thị không kết thúc nếu không enable.

*Edit contest*

- [x] Thêm icon thông tin (icon ?) bên cạnh nút Shuffle.
- [x] Chuyển checkbox Shuffle và nút Add vào panel có BackColor là gray.
- [x] Giao diện 6.2b: Chỉnh sửa backcolor, color, align cho các option.
- [x] Giảm kích thước cho icon thùng rác.
- [x] Nhấn vào a new question / from question bank / a random question hiện ra cửa sổ mới.
- [x] Thêm nút Close trên 2 form "from question bank" / "a random question". @NgxLama 
- [x] Thêm cursor "hand" khi di chuột vào các button / label link.
- [x] Thêm padding, căn chỉnh font, cỡ chữ cho hàng trong datagridview.

*From question bank*

- [x] Tăng kích thước cho combobox "Select a category".
- [x] Khóa move, sort cột.
- [x] Thêm padding, căn chỉnh font, cỡ chữ cho hàng trong datagridview.

*A random question*

- [x] Tăng font size.
- [x] Tăng kích thước cho combobox "Category". Giảm kích thước cho combobox "Number of ..."
- [x] Focus vào combobox "Category" và luôn reset về Default khi mở form.
- [x] Căn chỉnh combobox "Number of ..." thẳng hàng với các phần tử khác.
- [x] Không hiện các nút phân trang nếu để ở chế độ default.
- [x] Sửa lỗi ảnh cột image trong datagridview.
- [x] Thu nhỏ cột image trong datagridview.
- [x] Thêm padding, căn chỉnh font, cỡ chữ cho hàng trong datagridview.
- [x] Các nút phân trang cần sát nhau (tự code về location).
- [x] Chỉ hiện "Đã thêm ... câu hỏi" thay vì hiện đủ id các câu.
- [x] Lỗi hiển thị phân trang. @NgxLama 

*StartAttemptQuiz*

- [x] Điều chỉnh font, cỡ chữ, màu chữ, align cho các label phù hợp. @grintondh 
- [x] Thêm nút "EXPORT" bên cạnh Start attempt (sẽ hỏi thầy). Nhấn vào sẽ chuyển sang một form mới tương tự User Control ExportForm (tuy nhiên chỉ lấy các câu hỏi trong contest thay vì lấy toàn bộ). @NgxLama @grintondh 
- [x] Đóng form StartAttemptQuiz khi nhấn Start Attempt.

*PreviewQuizForm*

- [x] Điều chỉnh Backcolor cho toàn bộ phần "Question X Not yet answered...".
- [x] Điều chỉnh Backcolor và căn chỉnh padding cho phần câu hỏi.
- [x] Điều chỉnh Backcolor cho phần Quiz navigation.
- [x] Điều chỉnh Backcolor và Cursor cho Finish Attempt.
- [x] Nút Previous Page và Next page cần sát vào panel câu hỏi. Căn lề nút Previous Page thẳng hàng với box "Question ..."; Next Page thẳng hàng với box câu hỏi: 
![image](https://github.com/grintondh/LearningSystem/assets/90957755/69b1817c-85ed-4206-91fd-3b5bb8399fb0)
- [x] Không giới hạn về chiều cao Panel chứa các câu hỏi. Như hình dưới thì phần câu hỏi sẽ tràn xuống dưới form (2 nút Page cũng bị đẩy xuống theo), hiện scroll bar của FORM.
![image](https://github.com/grintondh/LearningSystem/assets/90957755/360254ee-c539-4484-8789-c2066b49a928)
- [x] Chỉnh màu Border (nếu được) cho Time Limit.
- [x] Tự động thêm A, B, C, D vào đầu các đáp án. @NgxLama 
- [x] Chỉnh căn lề cho radiobox / checkbox.
- [x] Tắt header (phần choice) cho các đáp án.
- [x] Khung "Question ..." bị cắt nếu câu hỏi ngắn:
![image](https://github.com/grintondh/LearningSystem/assets/90957755/406d1979-4eb3-4cbf-abb2-1854297db318)
- [x] Nếu chỉ có 1 page thì không hiện 2 nút Previous page / Next page.
- [x] Căn chỉnh font size, padding cho các câu hỏi. @grintondh 
- [x] Quiz navigation hơi bé. @Jeff-kxng 

*Xem đáp án*

- [x] Màn hình xem đáp án cũng phải sửa các yêu cầu như trên (toàn bộ của PreviewQuizForm).
- [x] Điểm và tỉ lệ đúng chỉ hiện lấy 2 chữ số phần thập phân.
- [x] Tổng phần trăm của các đáp án có thể vượt quá 100%. Ví dụ: 100%, 90% => cho ra 19 điểm. 
- [x] Điều chỉnh Backcolor và Cursor cho Finish Review.

*Lỗi Import (Bài 4)*
- [x] Lỗi nếu có nhiều hơn 1 dòng trống giữa các câu. @elio-perlman-13 
- [x] Lỗi nếu có kí tự khác (kể cả dấu cách) cạnh đáp án. @elio-perlman-13 
- [x] Lỗi khi để ảnh vào các choice. @elio-perlman-13 

**Hoàn thành trước 9/7**

*Merge và test*
- [x] Test toàn bộ các yêu cầu (trên và bảng test). @NGANnganngan  @Jeff-kxng 
- [x] Test toàn bộ các yêu cầu (bài 6 - 7). @NGANnganngan @Jeff-kxng 
- [x] Merge develop và release. @grintondh @NgxLama 
- [x] Tạo các file và nội dung test. @Jeff-kxng  @NGANnganngan.
- [x] Test toàn bộ các yêu cầu (Bài 1 - 9) với file test của thầy. @Jeff-kxng  @NGANnganngan

**Comment by NgxLama** [comment]
![image](https://github.com/grintondh/LearningSystem/assets/129042561/cffe18e2-dfe6-4197-9a59-b89a68a73ed2)
cái này thì tôi thấy trong mô tả của thầy căn phải nên tôi giữ nguyên nhé :((

![image](https://github.com/grintondh/LearningSystem/assets/129042561/751be9e3-52d9-43ce-b6f1-87c21dac7222)
cái này thì tôi cần thống nhất với bên bài 5 xem nếu k enable cái time thì sẽ nhận dạng ntn rồi tôi sửa lại sau nhé :vv

![image](https://github.com/grintondh/LearningSystem/assets/129042561/7aeb32cb-dd7f-4ac3-891e-8d2b48a8cb45)
mấy form này thì tôi lỡ code thành user control ấy nên giờ sửa thành form thì nó khá là khó sửa code lúc tạo đối tượng, nên tôi cũng chưa biết nên làm ntn :((

![image](https://github.com/grintondh/LearningSystem/assets/129042561/b9b71c65-180d-46d8-8d33-1517bdb83d32)
2 nút close tôi thấy trong mô tả BLV cũng có nên tôi giữ nguyên nhé

![image](https://github.com/grintondh/LearningSystem/assets/129042561/b5403eb8-c3b8-486f-affc-2744c5f911a7)
cái này tôi chưa hiểu rõ lắm ông mô tả kỹ hơn đc k :vv

![image](https://github.com/grintondh/LearningSystem/assets/129042561/e4301fce-a656-4752-9506-c107db90fcc3)
Cái này thì thêm A B C D vào đáp án chỉ có text thì oke nhưng mà nếu đọc từ chuỗi .rtf thì thêm vào có vẻ hơi gian nan á, để tôi tham khảo thêm bên Tú với Ngân xem nếu có ảnh thì mọi người cắt đc A B C D không rồi xử lý nhé

![image](https://github.com/grintondh/LearningSystem/assets/129042561/497d29cb-deaf-48a7-b5dc-934153d8a758)
cái này bủ dã man =(( tôi cũng k biết lúc chỉnh % đáp án mà chọn 100%, 90% thì lỗi do người dùng hay do bọn mình nữa :vv

**Comment by grintondh** [comment]
* Các thông tin kỳ thi: Nhưng mà ông nhìn nó lệch vl :))))
* Time limit: Trong class contest có TimeLimitEnable.
* Form + Nút Close: Thế hay làm button Close ở bên cạnh button Add question nhỉ, chứ để nút Close như kia nó k hợp lý ấy.
* Scroll bar: Thì như bây giờ cái panel chứa các câu hỏi nó đang bị cố định kích thước, nếu câu hỏi dài thì nó như cái hình ở trên kia. Còn theo ý tôi nó nên là như thế này:
![image](https://github.com/grintondh/LearningSystem/assets/90957755/0e9f0fc4-51bb-4536-bf10-1d22dcc4d393)
* Tự động thêm ABCD và tổng phần trăm: Cái này sẽ nghĩ cách sau.
