### ISSUE TITLE
Lỗi import file

### ISSUE THREAD

**Issue by grintondh** [grintondh/LearningSystem#5]
- Unhandle exception:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
>    at System.Collections.Generic.List`1.get_Item(Int32 index)
>    at Learning_System.ImportForm.CheckAikenFormat(List`1 lines) in E:\Github\LearningSystem\Learning System\Learning System\ImportForm.cs:line 61
>    at Learning_System.ImportForm.ImportForm_ImportBtn_Click(Object sender, EventArgs e) in E:\Github\LearningSystem\Learning System\Learning System\ImportForm.cs:line 214
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

File: (Đặc điểm dự đoán: không có ANSWER)
Một cộng một theo em bằng mấy?
A. 2
B. 3

**Comment by elio-perlman-13** [comment]
done a

**Comment by grintondh** [comment]
Đã fix.
